### PR TITLE
browsersync should default to HTTPS, fixes #19

### LINKED ISSUE #19: The addon is not working properly even with basic projects based on the HTTP protocol
OS: Windows 10 Pro
Docker: 20.10.17
DDEV: 1.21.1
Browser-Sync: 2.27.10

**Steps to reproduce this issue:**

1 - Create a directory named **test2** and create one file inside named **index.htm** (a boilerplate with some text).

2 - Install globally **browser-sync** with the following command ```npm install -g browser-sync```

3 - Open a Terminal in the current directory and run ``` browser-sync start --server --files "*"```. The browser opens loading the **index.htm** file. 

4 - Edit the **index.htm file**, save it and take a look at the browser window. Page reloads with the new content. In Windows PowerShell window you will see this information: 

screenshot-1

As you may see BrowserSync works fine. Let's test it with this DDEV addon.

5 - Create a new directory named **test1** and copy inside what is in the test2 directory (index.html).

6 - Run ```ddev config``` and choose a **php** for "Project Type". 

7 - Run ```ddev get drud/ddev-browsersync```. As an personal comment this message seems to be wrong "Please file issues and create pull requests there to improve it.". It should be "Please **report** issues ...".

8 - Run ```ddev start```. Now we can reach the project at https://test1.ddev.site **or** https://127.0.0.1:53834. As you can see both links use HTTPS protocol. 

9 - Run ```ddev browsersync``` and you will get this information in your Terminal window:

screenshot-2

10 - Keep <kbd>CTRL</kbd> pressed and click on the External link.  The browser opens loading the **index.htm** file. It is an HTTP connection.

11 - Edit the **index.htm file**, save it and take a look at the browser and Terminal window. **NOTHING HAPPENS**, the browser is not reloading and there are no new lines in Broswersync console. If we take a look in the file **.ddev/browser-sync.js** we will see that **docroot** is mentioned in the **files** option. As the file index.html is in the docroot, any changes in it should be found in the browser window.

Therefore, this addon does not work even with the basic configuration on a project that only has an HTML file. It is not an HTTP/HTTPS issue because in the browser window I can load the **index.html** page with both HTTP and HTTPS protocols. I hope based on this report to investigate and find a fix.

Also if this addon will not be updated ASAP for HTTPS proctol it is useless. In order to use it, maybe DDEV should have a question related to the desired protocol when creating the configuration file, otherwise in the case of this addon few know which files to modify to use the HTTP protocol only, the situation in which DDEV's purpose to provide a simple and fast interface with Docker is no longer valid. This can be discussed on the DDEV project page.

### PR DESCRIPTION
**Pull request by tyler36**
Fixes 
* #19

Currently, browsersync is configured to run on the HTTP. This is not optimal.

This PR changes browsersync to use the HTTPS protocal instead.

Note: When starting browsersync, it reports the "External URL" has HTTP.  I tried adding `HTTPS: true` to the config file but this resulted in a broken DDEV (502)

### CODE REVIEW

**Comment by rfay** [comment]
Does this mean you figured it out, or that you still couldn't make it work on https?

**Comment by tyler36** [comment]
This is working locally for me.

**Comment by tyler36** [comment]
Browsersync is running on HTTPS protocal in the browser. The CLI reports to running on HTTP though. It would be nice to have that correct but I think it might be the reverse  proxy stuff?

**Comment by rfay** [comment]
Looks like maybe some work remaining to do on tests?

**Review by rfay — CHANGES_REQUESTED** [review]
Well, it definitely works, but it will be too confusing to people. 

Could we at least change `ddev browsersync` command to output the true information? Maybe it can say at the top, before launching browsersync "IT WILL BE HTTP NOT HTTP" :) and give a good URL.  It might be possible to do something more sophisticated than that.

I think you already know that the reason it won't work by telling *browsersync* to use https is that then the ddev-router can't trust (or even decrypt) the https content. 

So the problem is just that we're letting browsersync provide inadequate information, and we need to figure out a way around that. 

I think it would be good to add more to the README about editing browser-sync.js as well. And how about adding "web" as one of the listed items/

**Comment by ADDISON74** [comment]
I did the changes to expose the new ports in ```docker-compose.browsersync.yaml```. Here are the test results for different scenarios.

1 - Opening ```https://browsersync.ddev.site:3000``` in the browser. As you may see any changes in the **index.html** file are loaded in the browser window.

1 - HTTPS

2 - By opening ```http://browsersync.ddev.site:3000``` in the browser (the BrowserSync External link) we get a 400 error.

2 - BS LINK

3 - By opening ```http://browsersync.ddev.site``` in the browser (the DDEV link using HTTP protocol) BrowserSync detects the changes in the file but it is not reloading the browser window content.

3 - HTTP LINK

In order to display **https** instead of **http** in the **External** link of the BrowserSync console we should add this option ```https: true``` in the ```browser-sync.js file```, but if we do this you may see what happens bellow. BrowserSync detects the changes in the ```index.html file```, but accessing the **External** link in the browser produces a 502 error.

4 - HTTPS ON

As a first conclusion after these scenarios. Changing the ports was beneficial, now the addon can also be used with HTTPS. The issue that needs to be solved is related to the **External** link displayed by BrowserSync in the console and which creates confusion but also errors in the situation in which it is used.

**Comment by tyler36** [comment]
Not sure why the tests are failing :(

**Comment by rfay** [comment]
FYI it's worth thinking about allowing HTTPS communication between ddev-webserver and ddev-router, but that wouldn't fundamentally solve the problem here, because the bound port (443) by default might be changed.

Thanks for all the work on this.

**Comment by rfay** [comment]
This PR can be tested with `ddev get https://github.com/tyler36/ddev-browsersync/tarball/tyler36/https-support/`

**Comment by ursbraem** [comment]
I `got` the PR and encountered no issues so far

**Comment by rfay** [comment]
Doggone those tests :)

**Comment by rfay** [comment]
Will definitely review and take a look at tests. Just under the gun to get the traefik stuff done for a major release. Thanks for your patience!

**Comment by tyler36** [comment]
Closing this in favor of #31

**Comment by tyler36** [comment]
Sorry. #31 was a PR to this PR. Re-opening.

**Pull request merged**
