### PR TITLE
add support for additional hostnames

### PR DESCRIPTION
**Pull request by tyler36**
Addreses #27

I'm not sure how many people are using additional hostnames. I assume people would prefer to see their project url instead of an IP in their terminal.

### CODE REVIEW

**Comment by tyler36** [comment]
This breaks auto-updates by asking people to remove "ddev-generated".. I'm not sure if this an ideal tradeoff.

**Comment by tyler36** [comment]
Refactored to support additional host out of the box

**Comment by rfay** [comment]
Congrats!

**Comment by tyler36** [comment]
I'm actually restesting it now ... and it doesn't appear to be working. I might need to revert it.

**Pull request merged**
